site_name: OPTIMake
site_url: https://docs.optimake.net
site_author: Orbit
site_description: Build Your Ultrafast Solver

# Repository
# repo_name: OPTIMake/client
# repo_url: https://github.com/optimake/client

# Copyright
copyright: Copyright &copy; 2023 - 2024 OPTIMake 

# Configuration
theme:
  name: 'material'
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  icon:
    repo: fontawesome/brands/github
  logo: assets/logo.png
  favicon: assets/favicon.png


extra:
  generator: false
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
  #   - icon: fontawesome/brands/docker
  #     link: https://hub.docker.com/r/squidfunk/mkdocs-material/
  #   - icon: fontawesome/brands/python
  #     link: https://pypi.org/project/mkdocs-material/
  #   - icon: fontawesome/brands/mastodon
  #     link: https://fosstodon.org/@optimake
  #  - icon: fontawesome/brands/github
  #    link: https://github.com/optimake
  #  - icon: fontawesome/brands/gitlab
  #    link: https://gitlab.com/optimake
    - icon: fontawesome/brands/zhihu
      link: https://zhihu.com/optimake
    - icon: fontawesome/brands/weibo
      link: https://weibo.com/optimake
    - icon: fontawesome/brands/bilibili
      link: https://bilibili.com/optimake
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/optimake
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/optimake
      

    

# Plugins
plugins:
  # - glightbox
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date-localized:
      #  enabled: !ENV [CI, false]
      enable_creation_date: true
      type: date

nav:
  - 介绍: introduction.md
  # - 算法特性: features.md
  - 安装方法: installation.md
  - 建模接口: interfaces.md
  - 代码生成: codegen.md
  - 代码部署: deploy.md
  - 应用案例:
      - Flight: examples/flight.md
      - Missile Guidance: examples/missile_guidance.md
  - FAQ: faq.md



markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - admonition
  - footnotes
  - codehilite
  - attr_list
  - md_in_html

google_analytics:
  - 'UA-120133947-1'
  - 'auto'
  
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
  - stylesheets/extra.css
